# Generated by Django 3.1 on 2021-03-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usermessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
