# Generated by Django 3.1 on 2021-03-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_parsoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParsOc',
        ),
    ]
